version: '3'

services:
  # Database
  db:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - site
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    env_file:
      - ".env"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    networks:
      - site
  # web
  web:
    image: php:7.2.2-apache
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    networks:
      - site
    stdin_open: true
    tty: true
  # job
  pythonjob:
      build: .
      networks:
        - site
      tty: true
      stdin_open: true
networks:
  site:
volumes:
  db_data:
